name: Q-STAR CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout du dépôt
      uses: actions/checkout@v3

    - name: 🐍 Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 pytest

    - name: ✅ Tests unitaires avec Pytest
      run: |
        pytest tests/ || pytest test_pipeline_evaluator.py

    - name: 🔍 Analyse de code avec Flake8
      run: |
        flake8 qstar --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 qstar --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: 🎨 Formatage avec Black
      run: |
        black --check qstar

    # Optionnel : création d'image Docker pour test
    #- name: 🐳 Build Docker image (optionnel)
    #  run: docker build -t qstar-test .
